version: '3.8'
services:
  database:
    ports:
    - "2345:5432"
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh:z
